# Generated by Django 3.0 on 2022-02-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('merch', '0001_initial'),
        ('users', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.AddField(
            model_name='typeset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeSet_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='typeset',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='TypeSet_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='typeset',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='TypeSet_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
        migrations.AddField(
            model_name='typeset',
            name='merchset',
            field=models.ForeignKey(blank=True, help_text='顾客群（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='typeset_merchset', to='merch.MerchSet', verbose_name='顾客群'),
        ),
        migrations.AddField(
            model_name='merchtypechild',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchTypeChild_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='merchtypechild',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='MerchTypeChild_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='merchtypechild',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchTypeChild_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
        migrations.AddField(
            model_name='merchtypechild',
            name='merchtype',
            field=models.ForeignKey(blank=True, help_text='品类（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchtypechild_merchtype', to='merch.MerchType', verbose_name='品类'),
        ),
        migrations.AddField(
            model_name='merchtype',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchType_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='merchtype',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='MerchType_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='merchtype',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchType_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
        migrations.AddField(
            model_name='merchtype',
            name='typeset',
            field=models.ForeignKey(blank=True, help_text='品类组（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchtype_typeset', to='merch.TypeSet', verbose_name='品类组'),
        ),
        migrations.AddField(
            model_name='merchset',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchSet_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='merchset',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='MerchSet_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='merchset',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='MerchSet_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
    ]
