# Generated by Django 3.0 on 2022-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('merch', '0002_auto_20220208_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='merchset',
            options={'ordering': ['-id'], 'verbose_name': '顾客群', 'verbose_name_plural': '顾客群'},
        ),
        migrations.AlterModelOptions(
            name='merchtype',
            options={'ordering': ['-id'], 'verbose_name': '品类', 'verbose_name_plural': '品类'},
        ),
        migrations.AlterModelOptions(
            name='merchtypechild',
            options={'ordering': ['-id'], 'verbose_name': '子品类', 'verbose_name_plural': '子品类'},
        ),
        migrations.AlterModelOptions(
            name='typeset',
            options={'ordering': ['-id'], 'verbose_name': '品类组', 'verbose_name_plural': '品类组'},
        ),
    ]
