# Generated by Django 3.0 on 2022-02-07 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Files',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, help_text='文件名称', max_length=255, verbose_name='文件名称')),
                ('fix', models.CharField(blank=True, help_text='后缀名', max_length=30, verbose_name='后缀名')),
                ('size', models.CharField(blank=True, help_text='文件大小', max_length=30, null=True, verbose_name='文件大小')),
                ('path', models.FileField(blank=True, help_text='文件路径（FileField）', null=True, upload_to='files/2022_02', verbose_name='文件路径')),
                ('with_models', models.CharField(default='wares', help_text='对应模块（CharField）', max_length=60, verbose_name='对应模块')),
                ('models_id', models.PositiveIntegerField(blank=True, help_text='模块ID(PositiveIntegerField)', null=True, verbose_name='模块ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '文件',
                'verbose_name_plural': '文件',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='图片名称（CharField）', max_length=60, verbose_name='图片名称')),
                ('img', models.ImageField(blank=True, help_text='图片（ImageField）', null=True, upload_to='imgs/2022_02', verbose_name='图片')),
                ('height', models.PositiveIntegerField(blank=True, help_text='图片高度(PositiveIntegerField)', null=True, verbose_name='图片高度')),
                ('with_models', models.CharField(default='wares', help_text='对应模块（CharField）', max_length=60, verbose_name='对应模块')),
                ('models_id', models.PositiveIntegerField(blank=True, help_text='模块ID(PositiveIntegerField)', null=True, verbose_name='模块ID')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '图片',
                'verbose_name_plural': '图片',
                'ordering': ['-id'],
            },
        ),
    ]
