# Generated by Django 3.0 on 2022-02-07 18:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('auth', '0011_update_proxy_permissions'),
        ('files', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='images',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='Images_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='images',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
        migrations.AddField(
            model_name='files',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_cb', to='users.UserExtension', verbose_name='创建人ID'),
        ),
        migrations.AddField(
            model_name='files',
            name='group',
            field=models.ManyToManyField(blank=True, help_text='可见分组', related_name='Files_group', to='auth.Group', verbose_name='可见分组'),
        ),
        migrations.AddField(
            model_name='files',
            name='last_edited_by',
            field=models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='files_eb', to='users.UserExtension', verbose_name='最后编辑人ID'),
        ),
    ]
