# Generated by Django 3.0 on 2022-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_auto_20220208_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='files',
            options={'ordering': ['-id'], 'verbose_name': '文件管理', 'verbose_name_plural': '文件管理'},
        ),
        migrations.AlterModelOptions(
            name='images',
            options={'ordering': ['-id'], 'verbose_name': '图片管理', 'verbose_name_plural': '图片管理'},
        ),
    ]
