# Generated by Django 3.0 on 2022-05-14 01:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_auto_20220301_1428'),
    ]

    operations = [
        migrations.AlterField(
            model_name='files',
            name='path',
            field=models.FileField(blank=True, help_text='文件路径（FileField）', null=True, upload_to='files/%Y/%m/', verbose_name='文件路径'),
        ),
        migrations.AlterField(
            model_name='images',
            name='img',
            field=models.ImageField(blank=True, help_text='图片（ImageField）', null=True, upload_to='imgs/%Y/%m/', verbose_name='图片'),
        ),
    ]
