# Generated by Django 3.0 on 2022-02-24 16:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20220220_1402'),
    ]

    operations = [
        migrations.CreateModel(
            name='SysImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='名称（CharField）', max_length=60, verbose_name='名称')),
                ('img', models.ImageField(blank=True, help_text='图片（ImageField）', null=True, upload_to='sys_imgs/2022_02', verbose_name='图片')),
                ('height', models.PositiveIntegerField(blank=True, help_text='图片高度(PositiveIntegerField)', null=True, verbose_name='图片高度')),
                ('path', models.CharField(blank=True, help_text='对应地址（CharField）', max_length=60, verbose_name='对应地址')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sysimages_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Sysimages_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
            ],
            options={
                'verbose_name': '图片管理',
                'verbose_name_plural': '图片管理',
                'ordering': ['-id'],
            },
        ),
    ]
