# Generated by Django 3.0 on 2022-02-24 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sysimages',
            name='with_models',
            field=models.CharField(default='page_urls', help_text='对应模块（CharField）', max_length=60, verbose_name='对应模块'),
        ),
    ]
