# Generated by Django 3.0 on 2022-02-24 17:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0002_sysimages_with_models'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sysimages',
            options={'ordering': ['-id'], 'verbose_name': '系统配置', 'verbose_name_plural': '系统配置'},
        ),
    ]
