# Generated by Django 3.0 on 2022-03-01 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0004_auto_20220225_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sysimages',
            name='img',
            field=models.ImageField(blank=True, help_text='图片（ImageField）', null=True, upload_to='sys_imgs/2022_03', verbose_name='图片'),
        ),
    ]
