# Generated by Django 3.0 on 2022-02-20 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_auto_20220220_1402'),
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0004_auto_20220220_1402'),
        ('stock', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock', models.IntegerField(blank=True, default=0, help_text='现存库存（CharField）', null=True, verbose_name='现存库存')),
                ('waystock', models.IntegerField(blank=True, default=0, help_text='在途库存（CharField）', null=True, verbose_name='在途库存')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='Stock_group', to='auth.Group', verbose_name='可见分组')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Stock_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('storage', models.ForeignKey(blank=True, help_text='仓库（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storage', to='stock.Storage', verbose_name='仓库')),
                ('waresku', models.ForeignKey(blank=True, help_text='商品SKU（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='waresku', to='wares.WareSKU', verbose_name='商品SKU')),
            ],
            options={
                'verbose_name': '仓储库存',
                'verbose_name_plural': '仓储库存',
                'ordering': ['storage__code', 'waresku__code'],
            },
        ),
    ]
