# Generated by Django 3.0 on 2022-02-20 09:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock', '0002_stock'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='stock',
            options={'ordering': ['storage__code', 'waresku__code'], 'verbose_name': '存储库存', 'verbose_name_plural': '存储库存'},
        ),
    ]
