# Generated by Django 3.0 on 2022-02-07 18:05

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('files', '0002_auto_20220208_0205'),
        ('users', '0001_initial'),
        ('supply', '0002_auto_20220208_0205'),
        ('merch', '0002_auto_20220208_0205'),
    ]

    operations = [
        migrations.CreateModel(
            name='Wares',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='品名（CharField）', max_length=60, verbose_name='品名')),
                ('code', models.CharField(blank=True, help_text='货号（CharField）', max_length=255, verbose_name='货号')),
                ('style', models.CharField(blank=True, help_text='（CharField）', max_length=255, verbose_name='特征/款式')),
                ('quality', models.CharField(blank=True, help_text='质地（CharField）', max_length=255, verbose_name='质地')),
                ('weight', models.DecimalField(blank=True, decimal_places=2, help_text='重量g（CharField）', max_digits=10, null=True, verbose_name='重量g')),
                ('land', models.CharField(blank=True, help_text='厚度cm（CharField）', max_length=255, verbose_name='厚度cm')),
                ('season', models.CharField(blank=True, help_text='季节（CharField）', max_length=255, verbose_name='季节')),
                ('bid', models.DecimalField(blank=True, decimal_places=2, help_text='进价（CharField）', max_digits=10, null=True, verbose_name='进价')),
                ('fix', models.DecimalField(blank=True, decimal_places=2, help_text='定价（CharField）', max_digits=10, null=True, verbose_name='定价')),
                ('delivery', models.DecimalField(blank=True, decimal_places=2, help_text='交货期/天（CharField）', max_digits=10, null=True, verbose_name='交货期/天')),
                ('base', models.PositiveIntegerField(blank=True, help_text='订货基数（CharField）', null=True, verbose_name='订货基数')),
                ('startorder', models.PositiveIntegerField(blank=True, help_text='起订量（CharField）', null=True, verbose_name='起订量')),
                ('way', models.CharField(blank=True, help_text='订货方式（CharField）', max_length=255, verbose_name='订货方式')),
                ('logistics', models.CharField(blank=True, help_text='物流（CharField）', max_length=255, verbose_name='物流')),
                ('instructions', mdeditor.fields.MDTextField(blank=True, verbose_name='使用说明')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='商品说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wares_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='Wares_group', to='auth.Group', verbose_name='可见分组')),
                ('img1', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img1', to='files.Images', verbose_name='图片1')),
                ('img2', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img2', to='files.Images', verbose_name='图片2')),
                ('img3', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img3', to='files.Images', verbose_name='图片3')),
                ('img4', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img4', to='files.Images', verbose_name='图片4')),
                ('img5', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img5', to='files.Images', verbose_name='图片5')),
                ('img6', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img6', to='files.Images', verbose_name='图片6')),
                ('img7', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img7', to='files.Images', verbose_name='图片7')),
                ('img8', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img8', to='files.Images', verbose_name='图片8')),
                ('img9', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='wares_img9', to='files.Images', verbose_name='图片9')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Wares_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('merchtypechild', models.ForeignKey(blank=True, help_text='子品类（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='merchtypechild', to='merch.MerchTypeChild', verbose_name='子品类')),
                ('supply', models.ForeignKey(blank=True, help_text='供应商（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wares_supply', to='supply.Supply', verbose_name='供应商')),
            ],
            options={
                'verbose_name': '01-商品',
                'verbose_name_plural': '01-商品',
                'ordering': ['-id'],
            },
        ),
        migrations.CreateModel(
            name='WareSKU',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='SKU（CharField）', max_length=60, verbose_name='SKU')),
                ('code', models.CharField(blank=True, help_text='色号（CharField）', max_length=255, verbose_name='色号')),
                ('color', models.CharField(blank=True, help_text='颜色（CharField）', max_length=255, verbose_name='颜色')),
                ('size', models.CharField(blank=True, help_text='码数（CharField）', max_length=255, verbose_name='码数')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WareSKU_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='WareSKU_group', to='auth.Group', verbose_name='可见分组')),
                ('img1', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img1', to='files.Images', verbose_name='图片1')),
                ('img2', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img2', to='files.Images', verbose_name='图片2')),
                ('img3', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img3', to='files.Images', verbose_name='图片3')),
                ('img4', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img4', to='files.Images', verbose_name='图片4')),
                ('img5', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img5', to='files.Images', verbose_name='图片5')),
                ('img6', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img6', to='files.Images', verbose_name='图片6')),
                ('img7', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img7', to='files.Images', verbose_name='图片7')),
                ('img8', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img8', to='files.Images', verbose_name='图片8')),
                ('img9', models.ForeignKey(blank=True, help_text='图片（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sku_img9', to='files.Images', verbose_name='图片9')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='WareSKU_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('wares', models.ForeignKey(blank=True, help_text='商品（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='wares', to='wares.Wares', verbose_name='商品')),
            ],
            options={
                'verbose_name': '02-色码',
                'verbose_name_plural': '02-色码',
                'ordering': ['-id'],
            },
        ),
    ]
