# Generated by Django 3.0 on 2022-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wares',
            options={'ordering': ['-id'], 'verbose_name': '商品', 'verbose_name_plural': '商品'},
        ),
        migrations.AlterModelOptions(
            name='waresku',
            options={'ordering': ['-id'], 'verbose_name': '色码', 'verbose_name_plural': '色码'},
        ),
    ]
