# Generated by Django 3.0 on 2022-02-21 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0002_auto_20220220_1402'),
    ]

    operations = [
        migrations.AddField(
            model_name='wares',
            name='url',
            field=models.TextField(blank=True, help_text='网址（TextField）', verbose_name='网址'),
        ),
    ]
