# Generated by Django 3.0 on 2022-02-23 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wares', '0003_wares_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wares',
            name='base',
        ),
        migrations.RemoveField(
            model_name='wares',
            name='bid',
        ),
        migrations.RemoveField(
            model_name='wares',
            name='delivery',
        ),
        migrations.RemoveField(
            model_name='wares',
            name='fix',
        ),
        migrations.RemoveField(
            model_name='wares',
            name='startorder',
        ),
        migrations.AddField(
            model_name='waresku',
            name='base',
            field=models.PositiveIntegerField(blank=True, help_text='订货基数（CharField）', null=True, verbose_name='订货基数'),
        ),
        migrations.AddField(
            model_name='waresku',
            name='bid',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='进价（CharField）', max_digits=10, null=True, verbose_name='进价'),
        ),
        migrations.AddField(
            model_name='waresku',
            name='delivery',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='交货期/天（CharField）', max_digits=10, null=True, verbose_name='交货期/天'),
        ),
        migrations.AddField(
            model_name='waresku',
            name='fix',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='定价（CharField）', max_digits=10, null=True, verbose_name='定价'),
        ),
        migrations.AddField(
            model_name='waresku',
            name='startorder',
            field=models.PositiveIntegerField(blank=True, help_text='起订量（CharField）', null=True, verbose_name='起订量'),
        ),
    ]
