# Generated by Django 3.0 on 2022-02-20 10:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='salesdetails',
            name='discount',
            field=models.DecimalField(blank=True, decimal_places=2, default=1, help_text='折扣（CharField）', max_digits=10, null=True, verbose_name='折扣'),
        ),
    ]
