# Generated by Django 3.0 on 2022-03-31 07:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_sales_promotion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sales',
            name='promotion',
        ),
    ]
