# Generated by Django 3.0 on 2022-03-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0005_remove_sales_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='sales',
            name='promotion',
            field=models.ManyToManyField(blank=True, help_text='促销计划', related_name='Sales_promotion', to='sales.Promotion', verbose_name='促销计划'),
        ),
    ]
