# Generated by Django 3.0 on 2022-03-31 17:09

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0006_sales_promotion'),
    ]

    operations = [
        migrations.AddField(
            model_name='promotion',
            name='content',
            field=mdeditor.fields.MDTextField(blank=True, verbose_name='方案详情'),
        ),
        migrations.AddField(
            model_name='promotion',
            name='types',
            field=models.CharField(choices=[('vip', '会员积分'), ('discount', '打折促销'), ('cut', '满减促销'), ('give', '买赠促销'), ('free', '满免促销'), ('other', '其他促销')], default='discount', help_text='促销类型', max_length=30, verbose_name='促销类型'),
        ),
    ]
