# Generated by Django 3.0 on 2022-03-31 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0007_auto_20220401_0109'),
    ]

    operations = [
        migrations.AlterField(
            model_name='promotion',
            name='content',
            field=models.TextField(blank=True, verbose_name='方案详情'),
        ),
    ]
