name: maifeng_app
description: maifeng app
publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1
environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  cupertino_icons: ^1.0.2
  get: ^4.5.1
  http: 0.13.4
  shared_preferences: ^2.0.8
  webview_flutter: ^3.0.0
  permission_handler: 8.3.0
  scan: 1.5.0 # 扫码
  flutter_form_builder: 7.0.0
  flutter_nfc_kit: ^3.1.0 # nfc
  qr_flutter: ^4.0.0 # 二维码生成
  disable_screenshots: 0.2.0
  fluttertoast: ^8.0.8
  connectivity_plus: ^2.1.0
  url_launcher: ^6.0.9 # flutter跳转外部链接
  charts_flutter: ^0.12.0 # flutter图表
  fl_chart: ^0.45.1 # flutter图表
  flutter_svg: ^1.0.3 # svg图片展示
  photo_view: ^0.12.0 # 图片展示
  animated_text_kit: ^4.2.1 # 艺术字
  flutter_slidable: ^1.2.0 # 可滑动列表项
  easy_popup: ^1.0.0 # 弹出层
  flutter_easyrefresh: ^2.2.1 # 下拉刷新
  search_choices: ^2.0.19 # 下拉选
  flutter_carousel_widget: ^1.0.3 # 滑动模块，轮播图
  find_dropdown: ^1.0.0 # 下拉
#  flutter_swiper: ^1.1.6 # 轮播图
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^1.0.0
  lints: 1.0.1
  build_runner: ^2.1.5
  flutter_test:
    sdk: flutter

flutter:
  assets:
    - assets/images/maifeng.png
    - assets/images/home1.png
    - assets/images/home2.png
    - assets/images/board1.png
    - assets/images/board2.png
    - assets/images/app1.png
    - assets/images/app2.png
    - assets/images/user1.png
    - assets/images/user2.png
    - assets/images/pay.png
    - assets/images/icons/gongsiquanbushengchandingdanguanli.png
    - assets/images/icons/chengpinrukuyuchukuguanli.png
    - assets/images/icons/xiaoshoudingdanshenhe.png
    - assets/images/icons/xinzengyugengxingongxudangan.png
    - assets/images/icons/weiwaijiagongcaigou.png
    - assets/images/icons/gongyingshangbaojiaguanli.png
    - assets/images/icons/shengchanbeiliaoyufaliao.png
    - assets/images/icons/caigoujichushezhi.png
    - assets/images/icons/Bomdanganguanli.png
    - assets/images/icons/bumenrenyuanguanli.png
    - assets/images/icons/wares1.png
    - assets/images/icons/churuku.png
    - assets/images/icons/gongyingshang.png
    - assets/images/icons/julei.png
    - assets/images/icons/shangpin.png
    - assets/images/icons/mendian.png
    - assets/images/icons/cangchu.png
    - assets/images/icons/xiaoshou.png
    - assets/images/icons/wenjian.png
    - assets/images/icons/yonghu.png
    - assets/images/icons/gonggao.png
    - assets/images/icons/search.png
    - assets/images/icons/search2.png
    - assets/images/icons/search3.png
    - assets/images/saoma.png
    - assets/images/shopping-basket.png
    - assets/images/shopping-cart.png
    - assets/images/credit-card.png
    - assets/images/list.png

  uses-material-design: true
