# Generated by Django 3.0 on 2022-02-20 06:02

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0004_auto_20220220_1402'),
        ('auth', '0011_update_proxy_permissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='LargeRegion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='大区（CharField）', max_length=60, verbose_name='大区')),
                ('code', models.CharField(blank=True, help_text='编号（CharField）', max_length=255, verbose_name='编号')),
                ('place', models.TextField(blank=True, help_text='位置（TextField）', verbose_name='位置')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LR_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='LR_group', to='auth.Group', verbose_name='可见分组')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LR_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('manage', models.ForeignKey(blank=True, help_text='负责人（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='LR_manage', to='users.UserExtension', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '经营大区',
                'verbose_name_plural': '经营大区',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='区域（CharField）', max_length=60, verbose_name='区域')),
                ('code', models.CharField(blank=True, help_text='编号（CharField）', max_length=255, verbose_name='编号')),
                ('place', models.TextField(blank=True, help_text='位置（TextField）', verbose_name='位置')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Region_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='Region_group', to='auth.Group', verbose_name='可见分组')),
                ('largeregion', models.ForeignKey(blank=True, help_text='大区（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='largeregion', to='store.LargeRegion', verbose_name='大区')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Region_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('manage', models.ForeignKey(blank=True, help_text='负责人（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Region_manage', to='users.UserExtension', verbose_name='负责人')),
            ],
            options={
                'verbose_name': '经营区域',
                'verbose_name_plural': '经营区域',
                'ordering': ['largeregion__name', 'name'],
            },
        ),
    ]
