# Generated by Django 3.0 on 2022-02-20 06:34

from django.db import migrations, models
import django.db.models.deletion
import mdeditor.fields


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0011_update_proxy_permissions'),
        ('users', '0004_auto_20220220_1402'),
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Shop',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='门店（CharField）', max_length=60, verbose_name='门店')),
                ('code', models.CharField(blank=True, help_text='编号（CharField）', max_length=255, verbose_name='编号')),
                ('place', models.TextField(blank=True, help_text='位置（TextField）', verbose_name='位置')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
                ('created_by', models.ForeignKey(blank=True, help_text='创建人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shop_cb', to='users.UserExtension', verbose_name='创建人ID')),
                ('group', models.ManyToManyField(blank=True, help_text='可见分组', related_name='Shop_group', to='auth.Group', verbose_name='可见分组')),
                ('last_edited_by', models.ForeignKey(blank=True, help_text='最后编辑人ID（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shop_eb', to='users.UserExtension', verbose_name='最后编辑人ID')),
                ('manage', models.ForeignKey(blank=True, help_text='负责人（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Shop_manage', to='users.UserExtension', verbose_name='负责人')),
                ('region', models.ForeignKey(blank=True, help_text='区域（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='store.LargeRegion', verbose_name='区域')),
            ],
            options={
                'verbose_name': '经营门店',
                'verbose_name_plural': '经营门店',
                'ordering': ['region__largeregion__name', 'region__name', 'name'],
            },
        ),
    ]
