# Generated by Django 3.0 on 2022-02-20 06:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_shop'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='region',
            field=models.ForeignKey(blank=True, help_text='区域（ForeignKey）', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='region', to='store.Region', verbose_name='区域'),
        ),
    ]
