# Generated by Django 3.0 on 2022-03-30 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20220330_2131'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='settype',
            field=models.CharField(blank=True, help_text='店群（CharField）', max_length=6, verbose_name='店群'),
        ),
    ]
