# Generated by Django 3.0 on 2022-03-30 17:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_shop_settype'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='size',
            field=models.CharField(choices=[('XS', '超小店'), ('S', '小店'), ('M', '中店'), ('L', '大店'), ('XL', '特大店'), ('O', '其他')], default='O', help_text='门店大小等级', max_length=5, verbose_name='门店大小等级'),
        ),
    ]
