# Generated by Django 3.0 on 2022-03-30 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_shop_size'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['region__largeregion__name', 'region__name', 'name', 'code'], 'verbose_name': '经营门店', 'verbose_name_plural': '经营门店'},
        ),
    ]
