# Generated by Django 3.0 on 2022-03-30 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_auto_20220331_0111'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shop',
            options={'ordering': ['code', 'region__largeregion__name', 'region__name', 'name'], 'verbose_name': '经营门店', 'verbose_name_plural': '经营门店'},
        ),
    ]
