# Generated by Django 3.0 on 2022-02-09 09:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userextension',
            name='created_by',
            field=models.ForeignKey(blank=True, help_text='创建人（ForeignKey）', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_cb', to='users.UserExtension', verbose_name='创建人'),
        ),
    ]
