# Generated by Django 3.0 on 2022-02-09 14:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_userextension_created_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userextension',
            name='created_by',
        ),
    ]
