# Generated by Django 3.0 on 2022-02-07 18:05

from django.db import migrations, models
import mdeditor.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Supply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='供应商（CharField）', max_length=60, verbose_name='供应商')),
                ('place', models.TextField(blank=True, help_text='位置/产地（TextField）', verbose_name='位置/产地')),
                ('tel', models.CharField(blank=True, help_text='电话（CharField）', max_length=11, verbose_name='电话')),
                ('scale', models.CharField(blank=True, choices=[('10', '10W'), ('50', '50W'), ('100', '100W'), ('200', '200W'), ('300', '300W'), ('500', '500W'), ('800', '800W'), ('1000', '1000W'), ('2000', '2000W'), ('3000', '3000W'), ('5000', '5000W'), ('10000', '10000W'), ('100000', '100000W')], default='10', help_text='规模（CharField）', max_length=11, verbose_name='规模')),
                ('grade', models.CharField(blank=True, choices=[('A', 'A级'), ('B', 'B级'), ('C', 'C级'), ('D', 'D级'), ('E', 'E级'), ('F', 'F级')], default='C', help_text='级别（CharField）', max_length=5, verbose_name='级别')),
                ('typ', models.CharField(blank=True, choices=[('factory', '工厂'), ('distribute', '经销'), ('wholesale', '批发'), ('other', '其他')], default='other', help_text='类型（CharField）', max_length=10, verbose_name='类型')),
                ('desc', mdeditor.fields.MDTextField(blank=True, verbose_name='说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, help_text='创建时间（DateTimeField）', null=True, verbose_name='创建时间')),
                ('last_edited_date', models.DateTimeField(auto_now=True, help_text='最后编辑时间（DateTimeField）', null=True, verbose_name='最后编辑时间')),
                ('deleted', models.CharField(choices=[('0', '未删除'), ('1', '已删除')], default='0', help_text='是否删除（CharField，可选值：0，1）', max_length=1, verbose_name='是否删除')),
            ],
            options={
                'verbose_name': '01-供应商',
                'verbose_name_plural': '01-供应商',
                'ordering': ['-id'],
            },
        ),
    ]
