# Generated by Django 3.0 on 2022-02-20 06:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('supply', '0002_auto_20220208_0205'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='supply',
            options={'ordering': ['-id'], 'verbose_name': '供应商', 'verbose_name_plural': '供应商'},
        ),
    ]
